/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ByteSymbolFlat2({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/8Byte_Symbol_3D_3c.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve009_1.geometry}
        material={materials["SVGMat.001"]}
      />
      <mesh
        geometry={nodes.Curve009_2.geometry}
        material={materials["SVGMat.002"]}
      />
      <mesh
        geometry={nodes.Curve009_3.geometry}
        material={materials["SVGMat.003"]}
      />
      <mesh
        geometry={nodes.Curve009_4.geometry}
        material={materials["SVGMat.004"]}
      />
      <mesh
        geometry={nodes.Curve009_5.geometry}
        material={materials["SVGMat.005"]}
      />
      <mesh
        geometry={nodes.Curve009_6.geometry}
        material={materials["SVGMat.006"]}
      />
      <mesh
        geometry={nodes.Curve009_7.geometry}
        material={materials["SVGMat.007"]}
      />
      <mesh
        geometry={nodes.Curve009_8.geometry}
        material={materials["SVGMat.008"]}
      />
      <mesh
        geometry={nodes.Curve009_9.geometry}
        material={materials["SVGMat.009"]}
      />
    </group>
  );
}

useGLTF.preload("/8Byte_Symbol_3D_3c.glb");
