/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Computer(props, ref) {
  // const group = useRef();
  const { nodes, materials } = useGLTF("/models/computer_c.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mac_1.geometry}
        material={materials.main}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mac_2.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mac_3.geometry}
        material={materials.screen}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mac_4.geometry}
        material={materials.vent}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mac_5.geometry}
        material={materials.logo}
      />
    </group>
  );
}

useGLTF.preload("/models/computer_c.glb");
