/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Handshake({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/handshake_emoji.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve030_1.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        geometry={nodes.Curve030_2.geometry}
        material={materials["Material.001"]}
      />
      <mesh geometry={nodes.Curve030_3.geometry} material={materials.SVGMat} />
      <mesh
        geometry={nodes.Curve030_4.geometry}
        material={materials["SVGMat.001"]}
      />
      <mesh
        geometry={nodes.Curve030_5.geometry}
        material={materials["SVGMat.002"]}
      />
      <mesh
        geometry={nodes.Curve030_6.geometry}
        material={nodes.Curve030_6.material}
      />
      <mesh
        geometry={nodes.Curve030_7.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Curve030_8.geometry}
        material={materials["SVGMat.003"]}
      />
      <mesh
        geometry={nodes.Curve030_9.geometry}
        material={materials["SVGMat.004"]}
      />
      <mesh
        geometry={nodes.Curve030_10.geometry}
        material={materials["SVGMat.005"]}
      />
      <mesh
        geometry={nodes.Curve030_11.geometry}
        material={materials["SVGMat.006"]}
      />
      <mesh
        geometry={nodes.Curve030_12.geometry}
        material={materials["SVGMat.007"]}
      />
    </group>
  );
}

useGLTF.preload("/models/handshake_emoji.glb");
