import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Zaysan79(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/Zaysan_79.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.31, 0]} rotation={[Math.PI / 2, 0, 0]} scale={5}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_1.geometry}
          material={materials["SVGMat.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_2.geometry}
          material={materials["SVGMat.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_3.geometry}
          material={materials["SVGMat.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_4.geometry}
          material={materials["SVGMat.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_5.geometry}
          material={materials["SVGMat.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_6.geometry}
          material={materials["SVGMat.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_7.geometry}
          material={materials["SVGMat.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_8.geometry}
          material={materials["SVGMat.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_9.geometry}
          material={materials["SVGMat.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_10.geometry}
          material={materials["SVGMat.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_11.geometry}
          material={materials["SVGMat.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_12.geometry}
          material={materials["SVGMat.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_13.geometry}
          material={materials["SVGMat.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_14.geometry}
          material={materials["SVGMat.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_15.geometry}
          material={materials["SVGMat.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_16.geometry}
          material={materials["SVGMat.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_17.geometry}
          material={materials["SVGMat.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_18.geometry}
          material={materials["SVGMat.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_19.geometry}
          material={materials["SVGMat.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_20.geometry}
          material={materials["SVGMat.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_21.geometry}
          material={materials["SVGMat.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_22.geometry}
          material={materials["SVGMat.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_23.geometry}
          material={materials["SVGMat.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_24.geometry}
          material={materials["SVGMat.024"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_25.geometry}
          material={materials["SVGMat.025"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_26.geometry}
          material={materials["SVGMat.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_27.geometry}
          material={materials["SVGMat.027"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_28.geometry}
          material={materials["SVGMat.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_29.geometry}
          material={materials["SVGMat.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_30.geometry}
          material={materials["SVGMat.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_31.geometry}
          material={materials["SVGMat.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_32.geometry}
          material={materials["SVGMat.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_33.geometry}
          material={materials["SVGMat.033"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_34.geometry}
          material={materials["SVGMat.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_35.geometry}
          material={materials["SVGMat.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_36.geometry}
          material={materials["SVGMat.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_37.geometry}
          material={materials["SVGMat.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_38.geometry}
          material={materials["SVGMat.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_39.geometry}
          material={materials["SVGMat.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_40.geometry}
          material={materials["SVGMat.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_41.geometry}
          material={materials["SVGMat.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_42.geometry}
          material={materials["SVGMat.042"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_43.geometry}
          material={materials["SVGMat.043"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_44.geometry}
          material={materials["SVGMat.044"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_45.geometry}
          material={materials["SVGMat.045"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_46.geometry}
          material={materials["SVGMat.046"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_47.geometry}
          material={materials["SVGMat.047"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_48.geometry}
          material={materials["SVGMat.048"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_49.geometry}
          material={materials["SVGMat.049"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_50.geometry}
          material={materials["SVGMat.050"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_51.geometry}
          material={materials["SVGMat.051"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_52.geometry}
          material={materials["SVGMat.052"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_53.geometry}
          material={materials["SVGMat.053"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_54.geometry}
          material={materials["SVGMat.054"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_55.geometry}
          material={materials["SVGMat.055"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_56.geometry}
          material={materials["SVGMat.056"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_57.geometry}
          material={materials["SVGMat.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_58.geometry}
          material={materials["SVGMat.058"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_59.geometry}
          material={materials["SVGMat.059"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_60.geometry}
          material={materials["SVGMat.060"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_61.geometry}
          material={materials["SVGMat.061"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_62.geometry}
          material={materials["SVGMat.062"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_63.geometry}
          material={materials["SVGMat.063"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_64.geometry}
          material={materials["SVGMat.064"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_65.geometry}
          material={materials["SVGMat.065"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_66.geometry}
          material={materials["SVGMat.066"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_67.geometry}
          material={materials["SVGMat.067"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_68.geometry}
          material={materials["SVGMat.068"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_69.geometry}
          material={materials["SVGMat.069"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_70.geometry}
          material={materials["SVGMat.070"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_71.geometry}
          material={materials["SVGMat.071"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_72.geometry}
          material={materials["SVGMat.072"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_73.geometry}
          material={materials["SVGMat.073"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_74.geometry}
          material={materials["SVGMat.074"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_75.geometry}
          material={materials["SVGMat.075"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_76.geometry}
          material={materials["SVGMat.076"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_77.geometry}
          material={materials["SVGMat.077"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_78.geometry}
          material={materials["SVGMat.078"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_79.geometry}
          material={materials["SVGMat.079"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_80.geometry}
          material={materials["SVGMat.080"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_81.geometry}
          material={materials["SVGMat.081"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_82.geometry}
          material={materials["SVGMat.082"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_83.geometry}
          material={materials["SVGMat.083"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_84.geometry}
          material={materials["SVGMat.084"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_85.geometry}
          material={materials["SVGMat.085"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_86.geometry}
          material={materials["SVGMat.086"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_87.geometry}
          material={materials["SVGMat.087"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_88.geometry}
          material={materials["SVGMat.088"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_89.geometry}
          material={materials["SVGMat.089"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_90.geometry}
          material={materials["SVGMat.090"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_91.geometry}
          material={materials["SVGMat.091"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_92.geometry}
          material={materials["SVGMat.092"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_93.geometry}
          material={materials["SVGMat.093"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_94.geometry}
          material={materials["SVGMat.094"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_95.geometry}
          material={materials["SVGMat.095"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_96.geometry}
          material={materials["SVGMat.096"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_97.geometry}
          material={materials["SVGMat.097"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_98.geometry}
          material={materials["SVGMat.098"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_99.geometry}
          material={materials["SVGMat.099"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_100.geometry}
          material={materials["SVGMat.100"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_101.geometry}
          material={materials["SVGMat.101"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_102.geometry}
          material={materials["SVGMat.102"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_103.geometry}
          material={materials["SVGMat.103"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_104.geometry}
          material={materials["SVGMat.104"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_105.geometry}
          material={materials["SVGMat.105"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_106.geometry}
          material={materials["SVGMat.106"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_107.geometry}
          material={materials["SVGMat.107"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_108.geometry}
          material={materials["SVGMat.108"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_109.geometry}
          material={materials["SVGMat.109"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_110.geometry}
          material={materials["SVGMat.110"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_111.geometry}
          material={materials["SVGMat.111"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_112.geometry}
          material={materials["SVGMat.112"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_113.geometry}
          material={materials["SVGMat.113"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_114.geometry}
          material={materials["SVGMat.114"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_115.geometry}
          material={materials["SVGMat.115"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_116.geometry}
          material={materials["SVGMat.116"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_117.geometry}
          material={materials["SVGMat.117"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_118.geometry}
          material={materials["SVGMat.118"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_119.geometry}
          material={materials["SVGMat.119"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_120.geometry}
          material={materials["SVGMat.120"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_121.geometry}
          material={materials["SVGMat.121"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_122.geometry}
          material={materials["SVGMat.122"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_123.geometry}
          material={materials["SVGMat.123"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_124.geometry}
          material={materials["SVGMat.124"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_125.geometry}
          material={materials["SVGMat.125"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_126.geometry}
          material={materials["SVGMat.126"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_127.geometry}
          material={materials["SVGMat.127"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_128.geometry}
          material={materials["SVGMat.128"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_129.geometry}
          material={materials["SVGMat.129"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_130.geometry}
          material={materials["SVGMat.130"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_131.geometry}
          material={materials["SVGMat.131"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_132.geometry}
          material={materials["SVGMat.132"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_133.geometry}
          material={materials["SVGMat.133"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_134.geometry}
          material={materials["SVGMat.134"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_135.geometry}
          material={materials["SVGMat.135"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_136.geometry}
          material={materials["SVGMat.136"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_137.geometry}
          material={materials["SVGMat.137"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_138.geometry}
          material={materials["SVGMat.138"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_139.geometry}
          material={materials["SVGMat.139"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_140.geometry}
          material={materials["SVGMat.140"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_141.geometry}
          material={materials["SVGMat.141"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_142.geometry}
          material={materials["SVGMat.142"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_143.geometry}
          material={materials["SVGMat.143"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_144.geometry}
          material={materials["SVGMat.144"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_145.geometry}
          material={materials["SVGMat.145"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_146.geometry}
          material={materials["SVGMat.146"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_147.geometry}
          material={materials["SVGMat.147"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_148.geometry}
          material={materials["SVGMat.148"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_149.geometry}
          material={materials["SVGMat.149"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_150.geometry}
          material={materials["SVGMat.150"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_151.geometry}
          material={materials["SVGMat.151"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_152.geometry}
          material={materials["SVGMat.152"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_153.geometry}
          material={materials["SVGMat.153"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_154.geometry}
          material={materials["SVGMat.154"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_155.geometry}
          material={materials["SVGMat.155"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_156.geometry}
          material={materials["SVGMat.156"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_157.geometry}
          material={materials["SVGMat.157"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_158.geometry}
          material={materials["SVGMat.158"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_159.geometry}
          material={materials["SVGMat.159"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_160.geometry}
          material={materials["SVGMat.160"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_161.geometry}
          material={materials["SVGMat.161"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_162.geometry}
          material={materials["SVGMat.162"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_163.geometry}
          material={materials["SVGMat.163"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_164.geometry}
          material={materials["SVGMat.164"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_165.geometry}
          material={materials["SVGMat.165"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_166.geometry}
          material={materials["SVGMat.166"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_167.geometry}
          material={materials["SVGMat.167"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_168.geometry}
          material={materials["SVGMat.168"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_169.geometry}
          material={materials["SVGMat.169"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_170.geometry}
          material={materials["SVGMat.170"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_171.geometry}
          material={materials["SVGMat.171"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_172.geometry}
          material={materials["SVGMat.172"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_173.geometry}
          material={materials["SVGMat.173"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_174.geometry}
          material={materials["SVGMat.174"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_175.geometry}
          material={materials["SVGMat.175"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_176.geometry}
          material={materials["SVGMat.176"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_177.geometry}
          material={materials["SVGMat.177"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_178.geometry}
          material={materials["SVGMat.178"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_179.geometry}
          material={materials["SVGMat.179"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_180.geometry}
          material={materials["SVGMat.180"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_181.geometry}
          material={materials["SVGMat.181"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_182.geometry}
          material={materials["SVGMat.182"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_183.geometry}
          material={materials["SVGMat.183"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_184.geometry}
          material={materials["SVGMat.184"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_185.geometry}
          material={materials["SVGMat.185"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_186.geometry}
          material={materials["SVGMat.186"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_187.geometry}
          material={materials["SVGMat.187"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_188.geometry}
          material={materials["SVGMat.188"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_189.geometry}
          material={materials["SVGMat.189"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_190.geometry}
          material={materials["SVGMat.190"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_191.geometry}
          material={materials["SVGMat.191"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_192.geometry}
          material={materials["SVGMat.192"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_193.geometry}
          material={materials["SVGMat.193"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_194.geometry}
          material={materials["SVGMat.194"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_195.geometry}
          material={materials["SVGMat.195"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_196.geometry}
          material={materials["SVGMat.196"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_197.geometry}
          material={materials["SVGMat.197"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_198.geometry}
          material={materials["SVGMat.198"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_199.geometry}
          material={materials["SVGMat.199"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_200.geometry}
          material={materials["SVGMat.200"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_201.geometry}
          material={materials["SVGMat.201"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_202.geometry}
          material={materials["SVGMat.202"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_203.geometry}
          material={materials["SVGMat.203"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_204.geometry}
          material={materials["SVGMat.204"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_205.geometry}
          material={materials["SVGMat.205"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_206.geometry}
          material={materials["SVGMat.206"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_207.geometry}
          material={materials["SVGMat.207"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_208.geometry}
          material={materials["SVGMat.208"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_209.geometry}
          material={materials["SVGMat.209"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_210.geometry}
          material={materials["SVGMat.210"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_211.geometry}
          material={materials["SVGMat.211"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_212.geometry}
          material={materials["SVGMat.212"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_213.geometry}
          material={materials["SVGMat.213"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_214.geometry}
          material={materials["SVGMat.214"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_215.geometry}
          material={materials["SVGMat.215"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_216.geometry}
          material={materials["SVGMat.216"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_217.geometry}
          material={materials["SVGMat.217"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_218.geometry}
          material={materials["SVGMat.218"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_219.geometry}
          material={materials["SVGMat.219"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_220.geometry}
          material={materials["SVGMat.220"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Zaysan_79.glb");
