import React, { forwardRef, Suspense, useRef } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import {
  useGLTF,
  OrbitControls,
  Float,
  QuadraticBezierLine,
  ContactShadows,
} from "@react-three/drei";
import * as THREE from "three";

const Computer = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/models/computer2_c.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.curvedScreen_1.geometry}
        material={materials.screen}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.curvedScreen_2.geometry}
        material={materials.vent}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.curvedScreen_3.geometry}
        material={materials.logo}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.curvedScreen_4.geometry}
        material={materials.main}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.curvedScreen_5.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
});

const Toadz1238 = forwardRef(({ children, ...props }, ref) => {
  const { nodes, materials } = useGLTF("/models/Toadz_1238.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[0, 0.14, 0]} rotation={[Math.PI / 2, 0, 0]} scale={6}>
        {children}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_1.geometry}
          material={materials["SVGMat.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_2.geometry}
          material={materials["SVGMat.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_3.geometry}
          material={materials["SVGMat.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_4.geometry}
          material={materials["SVGMat.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_5.geometry}
          material={materials["SVGMat.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_6.geometry}
          material={materials["SVGMat.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_7.geometry}
          material={materials["SVGMat.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_8.geometry}
          material={materials["SVGMat.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_9.geometry}
          material={materials["SVGMat.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_10.geometry}
          material={materials["SVGMat.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_11.geometry}
          material={materials["SVGMat.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_12.geometry}
          material={materials["SVGMat.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_13.geometry}
          material={materials["SVGMat.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_14.geometry}
          material={materials["SVGMat.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_15.geometry}
          material={materials["SVGMat.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_16.geometry}
          material={materials["SVGMat.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_17.geometry}
          material={materials["SVGMat.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_18.geometry}
          material={materials["SVGMat.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_19.geometry}
          material={materials["SVGMat.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_20.geometry}
          material={materials["SVGMat.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_21.geometry}
          material={materials["SVGMat.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_22.geometry}
          material={materials["SVGMat.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_23.geometry}
          material={materials["SVGMat.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_24.geometry}
          material={materials["SVGMat.024"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_25.geometry}
          material={materials["SVGMat.025"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_26.geometry}
          material={materials["SVGMat.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_27.geometry}
          material={materials["SVGMat.027"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_28.geometry}
          material={materials["SVGMat.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_29.geometry}
          material={materials["SVGMat.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_30.geometry}
          material={materials["SVGMat.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_31.geometry}
          material={materials["SVGMat.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_32.geometry}
          material={materials["SVGMat.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_33.geometry}
          material={materials["SVGMat.033"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_34.geometry}
          material={materials["SVGMat.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_35.geometry}
          material={materials["SVGMat.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_36.geometry}
          material={materials["SVGMat.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_37.geometry}
          material={materials["SVGMat.037"]}
        />
      </group>
    </group>
  );
});

const Toadz4883 = forwardRef(({ children, ...props }, ref) => {
  const { nodes, materials } = useGLTF("/models/Toadz_4883.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[50, 50, 50]}>
        {children}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_1.geometry}
          material={materials["SVGMat.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_2.geometry}
          material={materials["SVGMat.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_3.geometry}
          material={materials["SVGMat.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_4.geometry}
          material={materials["SVGMat.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_5.geometry}
          material={materials["SVGMat.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_6.geometry}
          material={materials["SVGMat.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_7.geometry}
          material={materials["SVGMat.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_8.geometry}
          material={materials["SVGMat.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_9.geometry}
          material={materials["SVGMat.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_10.geometry}
          material={materials["SVGMat.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_11.geometry}
          material={materials["SVGMat.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_12.geometry}
          material={materials["SVGMat.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_13.geometry}
          material={materials["SVGMat.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_14.geometry}
          material={materials["SVGMat.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_15.geometry}
          material={materials["SVGMat.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_16.geometry}
          material={materials["SVGMat.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_17.geometry}
          material={materials["SVGMat.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_18.geometry}
          material={materials["SVGMat.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_19.geometry}
          material={materials["SVGMat.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_20.geometry}
          material={materials["SVGMat.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_21.geometry}
          material={materials["SVGMat.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_22.geometry}
          material={materials["SVGMat.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_23.geometry}
          material={materials["SVGMat.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_24.geometry}
          material={materials["SVGMat.024"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_25.geometry}
          material={materials["SVGMat.025"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_26.geometry}
          material={materials["SVGMat.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_27.geometry}
          material={materials["SVGMat.027"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_28.geometry}
          material={materials["SVGMat.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_29.geometry}
          material={materials["SVGMat.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_30.geometry}
          material={materials["SVGMat.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_31.geometry}
          material={materials["SVGMat.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_32.geometry}
          material={materials["SVGMat.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_33.geometry}
          material={materials["SVGMat.033"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_34.geometry}
          material={materials["SVGMat.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_35.geometry}
          material={materials["SVGMat.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_36.geometry}
          material={materials["SVGMat.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_37.geometry}
          material={materials["SVGMat.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_38.geometry}
          material={materials["SVGMat.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_39.geometry}
          material={materials["SVGMat.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_40.geometry}
          material={materials["SVGMat.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_41.geometry}
          material={materials["SVGMat.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_42.geometry}
          material={materials["SVGMat.042"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_43.geometry}
          material={materials["SVGMat.043"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_44.geometry}
          material={materials["SVGMat.044"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_45.geometry}
          material={materials["SVGMat.045"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_46.geometry}
          material={materials["SVGMat.046"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_47.geometry}
          material={materials["SVGMat.047"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_48.geometry}
          material={materials["SVGMat.048"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_49.geometry}
          material={materials["SVGMat.049"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_50.geometry}
          material={materials["SVGMat.050"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_51.geometry}
          material={materials["SVGMat.051"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_52.geometry}
          material={materials["SVGMat.052"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_53.geometry}
          material={materials["SVGMat.053"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_54.geometry}
          material={materials["SVGMat.054"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_55.geometry}
          material={materials["SVGMat.055"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_56.geometry}
          material={materials["SVGMat.056"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_57.geometry}
          material={materials["SVGMat.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_58.geometry}
          material={materials["SVGMat.058"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_59.geometry}
          material={materials["SVGMat.059"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_60.geometry}
          material={materials["SVGMat.060"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_61.geometry}
          material={materials["SVGMat.061"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_62.geometry}
          material={materials["SVGMat.062"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_63.geometry}
          material={materials["SVGMat.063"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_64.geometry}
          material={materials["SVGMat.064"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_65.geometry}
          material={materials["SVGMat.065"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_66.geometry}
          material={materials["SVGMat.066"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_67.geometry}
          material={materials["SVGMat.067"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_68.geometry}
          material={materials["SVGMat.068"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_69.geometry}
          material={materials["SVGMat.069"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_70.geometry}
          material={materials["SVGMat.070"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_71.geometry}
          material={materials["SVGMat.071"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_72.geometry}
          material={materials["SVGMat.072"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_73.geometry}
          material={materials["SVGMat.073"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_74.geometry}
          material={materials["SVGMat.074"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_75.geometry}
          material={materials["SVGMat.075"]}
        />
      </group>
    </group>
  );
});

const Noun36 = forwardRef(({ children, ...props }, ref) => {
  const { nodes, materials } = useGLTF("models/Nouns_36.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[50, 50, 50]}>
        {children}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_1.geometry}
          material={materials["SVGMat.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_2.geometry}
          material={materials["SVGMat.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_3.geometry}
          material={materials["SVGMat.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_4.geometry}
          material={materials["SVGMat.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_5.geometry}
          material={materials["SVGMat.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_6.geometry}
          material={materials["SVGMat.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_7.geometry}
          material={materials["SVGMat.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_8.geometry}
          material={materials["SVGMat.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_9.geometry}
          material={materials["SVGMat.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_10.geometry}
          material={materials["SVGMat.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_11.geometry}
          material={materials["SVGMat.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_12.geometry}
          material={materials["SVGMat.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_13.geometry}
          material={materials["SVGMat.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_14.geometry}
          material={materials["SVGMat.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_15.geometry}
          material={materials["SVGMat.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_16.geometry}
          material={materials["SVGMat.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_17.geometry}
          material={materials["SVGMat.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_18.geometry}
          material={materials["SVGMat.019"]}
        />
      </group>
    </group>
  );
});

const Noun11 = forwardRef(({ children, ...props }, ref) => {
  const { nodes, materials } = useGLTF("/models/Nouns_11.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[50, 50, 50]}>
        {children}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_1.geometry}
          material={materials["SVGMat.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_2.geometry}
          material={materials["SVGMat.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_3.geometry}
          material={materials["SVGMat.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_4.geometry}
          material={materials["SVGMat.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_5.geometry}
          material={materials["SVGMat.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_6.geometry}
          material={materials["SVGMat.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_7.geometry}
          material={materials["SVGMat.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_8.geometry}
          material={materials["SVGMat.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_9.geometry}
          material={materials["SVGMat.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_10.geometry}
          material={materials["SVGMat.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_11.geometry}
          material={materials["SVGMat.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_12.geometry}
          material={materials["SVGMat.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_13.geometry}
          material={materials["SVGMat.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_14.geometry}
          material={materials["SVGMat.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_15.geometry}
          material={materials["SVGMat.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_16.geometry}
          material={materials["SVGMat.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_17.geometry}
          material={materials["SVGMat.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_18.geometry}
          material={materials["SVGMat.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_19.geometry}
          material={materials["SVGMat.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_20.geometry}
          material={materials["SVGMat.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_21.geometry}
          material={materials["SVGMat.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_22.geometry}
          material={materials["SVGMat.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_23.geometry}
          material={materials["SVGMat.024"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_24.geometry}
          material={materials["SVGMat.025"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_25.geometry}
          material={materials["SVGMat.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_26.geometry}
          material={materials["SVGMat.027"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_27.geometry}
          material={materials["SVGMat.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_28.geometry}
          material={materials["SVGMat.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_29.geometry}
          material={materials["SVGMat.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_30.geometry}
          material={materials["SVGMat.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_31.geometry}
          material={materials["SVGMat.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_32.geometry}
          material={materials["SVGMat.033"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_33.geometry}
          material={materials["SVGMat.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_34.geometry}
          material={materials["SVGMat.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_35.geometry}
          material={materials["SVGMat.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_36.geometry}
          material={materials["SVGMat.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_37.geometry}
          material={materials["SVGMat.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_38.geometry}
          material={materials["SVGMat.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_39.geometry}
          material={materials["SVGMat.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_40.geometry}
          material={materials["SVGMat.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_41.geometry}
          material={materials["SVGMat.042"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve001_42.geometry}
          material={materials["SVGMat.043"]}
        />
      </group>
    </group>
  );
});

const Toadz6232 = forwardRef(({ children, ...props }, ref) => {
  const { nodes, materials } = useGLTF("/models/Toadz_6232.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[0, 0.14, 0]} rotation={[Math.PI / 2, 0, 0]} scale={6}>
        {children}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_1.geometry}
          material={materials["SVGMat.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_2.geometry}
          material={materials["SVGMat.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_3.geometry}
          material={materials["SVGMat.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_4.geometry}
          material={materials["SVGMat.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_5.geometry}
          material={materials["SVGMat.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_6.geometry}
          material={materials["SVGMat.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_7.geometry}
          material={materials["SVGMat.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_8.geometry}
          material={materials["SVGMat.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_9.geometry}
          material={materials["SVGMat.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_10.geometry}
          material={materials["SVGMat.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_11.geometry}
          material={materials["SVGMat.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_12.geometry}
          material={materials["SVGMat.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_13.geometry}
          material={materials["SVGMat.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_14.geometry}
          material={materials["SVGMat.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_15.geometry}
          material={materials["SVGMat.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_16.geometry}
          material={materials["SVGMat.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_17.geometry}
          material={materials["SVGMat.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_18.geometry}
          material={materials["SVGMat.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_19.geometry}
          material={materials["SVGMat.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_20.geometry}
          material={materials["SVGMat.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_21.geometry}
          material={materials["SVGMat.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_22.geometry}
          material={materials["SVGMat.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_23.geometry}
          material={materials["SVGMat.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_24.geometry}
          material={materials["SVGMat.024"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_25.geometry}
          material={materials["SVGMat.025"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_26.geometry}
          material={materials["SVGMat.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_27.geometry}
          material={materials["SVGMat.027"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_28.geometry}
          material={materials["SVGMat.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_29.geometry}
          material={materials["SVGMat.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_30.geometry}
          material={materials["SVGMat.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_31.geometry}
          material={materials["SVGMat.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_32.geometry}
          material={materials["SVGMat.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_33.geometry}
          material={materials["SVGMat.033"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_34.geometry}
          material={materials["SVGMat.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_35.geometry}
          material={materials["SVGMat.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_36.geometry}
          material={materials["SVGMat.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_37.geometry}
          material={materials["SVGMat.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_38.geometry}
          material={materials["SVGMat.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_39.geometry}
          material={materials["SVGMat.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_40.geometry}
          material={materials["SVGMat.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_41.geometry}
          material={materials["SVGMat.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_42.geometry}
          material={materials["SVGMat.042"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_43.geometry}
          material={materials["SVGMat.043"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_44.geometry}
          material={materials["SVGMat.044"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_45.geometry}
          material={materials["SVGMat.045"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_46.geometry}
          material={materials["SVGMat.046"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_47.geometry}
          material={materials["SVGMat.047"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_48.geometry}
          material={materials["SVGMat.048"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_49.geometry}
          material={materials["SVGMat.049"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_50.geometry}
          material={materials["SVGMat.050"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_51.geometry}
          material={materials["SVGMat.051"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_52.geometry}
          material={materials["SVGMat.052"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_53.geometry}
          material={materials["SVGMat.053"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_54.geometry}
          material={materials["SVGMat.054"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_55.geometry}
          material={materials["SVGMat.055"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_56.geometry}
          material={materials["SVGMat.056"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_57.geometry}
          material={materials["SVGMat.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_58.geometry}
          material={materials["SVGMat.058"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_59.geometry}
          material={materials["SVGMat.059"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_60.geometry}
          material={materials["SVGMat.060"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_61.geometry}
          material={materials["SVGMat.061"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_62.geometry}
          material={materials["SVGMat.062"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_63.geometry}
          material={materials["SVGMat.063"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_64.geometry}
          material={materials["SVGMat.064"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_65.geometry}
          material={materials["SVGMat.065"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_66.geometry}
          material={materials["SVGMat.066"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_67.geometry}
          material={materials["SVGMat.067"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_68.geometry}
          material={materials["SVGMat.068"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_69.geometry}
          material={materials["SVGMat.069"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_70.geometry}
          material={materials["SVGMat.070"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_71.geometry}
          material={materials["SVGMat.071"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_72.geometry}
          material={materials["SVGMat.072"]}
        />
      </group>
    </group>
  );
});

const Toadz54 = forwardRef(({ children, ...props }, ref) => {
  const { nodes, materials } = useGLTF("/models/Toadz_54.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[0, 0.14, 0]} rotation={[Math.PI / 2, 0, 0]} scale={6}>
        {children}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_1.geometry}
          material={materials["SVGMat.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_2.geometry}
          material={materials["SVGMat.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_3.geometry}
          material={materials["SVGMat.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_4.geometry}
          material={materials["SVGMat.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_5.geometry}
          material={materials["SVGMat.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_6.geometry}
          material={materials["SVGMat.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_7.geometry}
          material={materials["SVGMat.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_8.geometry}
          material={materials["SVGMat.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_9.geometry}
          material={materials["SVGMat.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_10.geometry}
          material={materials["SVGMat.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_11.geometry}
          material={materials["SVGMat.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_12.geometry}
          material={materials["SVGMat.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_13.geometry}
          material={materials["SVGMat.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_14.geometry}
          material={materials["SVGMat.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_15.geometry}
          material={materials["SVGMat.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_16.geometry}
          material={materials["SVGMat.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_17.geometry}
          material={materials["SVGMat.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_18.geometry}
          material={materials["SVGMat.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_19.geometry}
          material={materials["SVGMat.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_20.geometry}
          material={materials["SVGMat.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve_21.geometry}
          material={materials["SVGMat.021"]}
        />
      </group>
    </group>
  );
});

function Cable({
  start,
  end,
  v1 = new THREE.Vector3(),
  v2 = new THREE.Vector3(),
  color = "#ff2060",
  linewidth = 2.5,
  Dashed,
}) {
  const ref = useRef();
  useFrame(
    () =>
      ref.current.setPoints(
        start.current.getWorldPosition(v1),
        end.current.getWorldPosition(v2)
      ),
    []
  );
  return (
    <QuadraticBezierLine
      ref={ref}
      lineWidth={linewidth}
      color={color}
      dashed={Dashed}
    />
  );
}

const ProcessModelViewer = () => {
  const comp = useRef();
  const toad1238 = useRef();
  const toad4883 = useRef();
  const noun36 = useRef();
  const noun11 = useRef();
  const toad6232 = useRef();
  const toad54 = useRef();

  return (
    <>
      <Canvas camera={{ fov: 8.5, position: [0, 9, -50] }}>
        <Suspense fallback={null}>
          <ambientLight intensity={0.8} />
          <directionalLight position={[0, 20, 0]} intensity={1.8} />
          <pointLight position={[6, -0.5, 0.6]} intensity={1.2} />
          <directionalLight position={[3, 8, 0.6]} intensity={0.6} />

          <pointLight position={[-4, -2, 0]} intensity={1.8} />

          {/* <Computer rotation={[49.8, 65.5, 0]} position={[0, 0, 0]} /> */}
          <Float scale={1} position={[0, -0.5, 0]} rotation={[0, 0, 0]}>
            <Computer rotation={[49.8, 65.5, 0]} ref={comp} />
          </Float>

          <Float
            position={[6, -3.2, -1]}
            rotation={[0, Math.PI / 1, 0]}
            rotationIntensity={2}
            floatIntensity={3}
            speed={1.5}
          >
            <Toadz1238 scale={5}>
              <object3D ref={toad1238} />
            </Toadz1238>
          </Float>

          <Float
            position={[-6, 2, -1]}
            rotation={[0, Math.PI / 1, 0]}
            rotationIntensity={2}
            floatIntensity={3}
            speed={3}
          >
            <Toadz4883 scale={0.5}>
              <object3D ref={toad4883} />
            </Toadz4883>
          </Float>

          <Float
            position={[6, 2, -1]}
            rotation={[0, 0, 0]}
            rotationIntensity={2}
            floatIntensity={3}
            speed={1.5}
          >
            <Noun36 scale={0.45}>
              <object3D ref={noun36} />
            </Noun36>
          </Float>

          <Float
            position={[-6, -2, -1]}
            rotation={[0, Math.PI / 1, 0]}
            rotationIntensity={2}
            floatIntensity={3}
            speed={1.5}
          >
            <Noun11 scale={0.5}>
              <object3D ref={noun11} />
            </Noun11>
          </Float>

          <Float
            position={[-9, 0, -1]}
            rotation={[0, Math.PI, 0]}
            rotationIntensity={2}
            floatIntensity={3}
            speed={1.5}
          >
            <Toadz6232 scale={4}>
              <object3D ref={toad6232} />
            </Toadz6232>
          </Float>

          <Float
            position={[9, -2, -1]}
            rotation={[0, Math.PI, 0]}
            rotationIntensity={2}
            floatIntensity={3}
            speed={1.5}
          >
            <Toadz54 scale={5}>
              <object3D ref={toad54} />
            </Toadz54>
          </Float>

          <Cable start={comp} end={toad1238} color={"#D7842E"} />
          <Cable start={toad1238} end={comp} color={"#000"} />

          <Cable
            start={comp}
            end={toad4883}
            color={"#00e5ff"}
            linewidth={2.5}
            dashed={true}
          />
          <Cable start={toad4883} end={comp} linewidth={3.5} />

          <Cable start={comp} end={noun36} color={"#7FB0FA"} linewidth={2.5} />
          <Cable start={noun36} end={comp} color={"#585659"} linewidth={3.5} />

          <Cable start={comp} end={noun11} color={"#4AEA68"} linewidth={2.5} />
          <Cable start={noun11} end={comp} color={"#73777E"} linewidth={3.5} />

          <Cable start={comp} end={toad6232} color={"#A020F0"} linewidth={4} />

          <Cable start={comp} end={toad54} color={"#FF2400"} linewidth={5} />

          <ContactShadows
            rotation-x={Math.PI / 2}
            position={[0, -1.4, 0]}
            opacity={0.75}
            width={10}
            height={10}
            blur={2.6}
            far={2}
          />
          <OrbitControls
            enableZoom={false}
            enablePan={true}
            enableRotate={true}
          />
          {/* <Environment preset="city" /> */}
          {/* <Environment files="studio_1k.hdr" path="/hdris/" preset={null} /> */}
        </Suspense>
      </Canvas>
    </>
  );
};

export default ProcessModelViewer;
